AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  jarvis

  Sample SAM Template for jarvis

Resources:
  JarvisFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Architectures:
        - x86_64
      CodeUri: ./
      Description: notify new contents delivered by streaming services
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Description: Exec JarvisFunction every hour everyday.
            Enabled: true
            Name: exec-jarvis-every-hour-everyday
            Schedule: cron(30 * * * ? *)
      FunctionName: Jarvis
      Handler: jarvis
      MemorySize: 256
      PackageType: Zip
      Runtime: go1.x
      Timeout: 180
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
    Metadata:
      BuildMethod: makefile

  JarvisErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - Ref: JarivsSNSTopic
      AlarmDescription: Monitor Jarvis of lambda function.
      AlarmName: jarvis-alarm
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref JarvisFunction
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 3600
      Statistic: Sum
      Threshold: 1

  JarivsSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: candy12t+aws_jarivs_alarm@gmail.com
          Protocol: email
      TopicName: JarivsAlertSNS
